<%@ Page Language="C#" MasterPageFile="~/addins_app/app_child.master" AutoEventWireup="true" CodeFile="ObitsAdmin.aspx.cs" Inherits="ObitsAdmin" %>

<asp:Content id="DefaultHead" ContentPlaceHolderID="ContentPlaceHolderDefaultHead" runat="server">
   <link rel="stylesheet" href="assets/css/default.css" media="screen" type="text/css" />
 </asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="headerPlaceHolder" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <div id="mainContent">
    <table class="obaTableCls">
				<tr>
					<td valign="middle" colspan="4">
						<table>
							<tr>
								<td><asp:textbox id="txtNewRealname" runat="server" Height="26px" Width="232px" CssClass="txtBox"></asp:textbox></td>
							</tr>
							<tr>
								<td><asp:button id="btnNewName" runat="server" Text=" 1. Enter New Real Name" 
                                        Width="231px" onclick="btnNewName_Click" CssClass="btnBox"></asp:button></td>
							</tr>
							<tr>
								<td>
									<asp:Label id="lblSuccess" runat="server" Width="228px" ForeColor="Red" Font-Bold="True" Visible="False">New name entered successfully!</asp:Label>
									<asp:TextBox id="txtNewID" runat="server" Height="27px" Width="77px" Visible="False" CssClass="txtBox"></asp:TextBox></td>
							</tr>
						</table>
						<asp:Label id="lblDupe" runat="server" Visible="False" Font-Bold="True" ForeColor="Red"></asp:Label>
					</td>
					<td>
						<table class="obaTableCls2" >
							<tr>
								<td>
									<table class="obaTableCls3" >
										<tr>
											<td><asp:label id="Label5" runat="server">Type a name</asp:label></td>
										</tr>
										<tr>
											<td>
                                                    <asp:TextBox ID="txtNameList" runat="server" Width="225px" CssClass="txtBox"></asp:TextBox>
                                                    <ajaxToolkit:AutoCompleteExtender ID="ace" runat="server" TargetControlID="txtNameList" 
                                                        ServiceMethod="GetCompletionList" ServicePath="AutoComplete.asmx" MinimumPrefixLength="3"
                                                        CompletionSetCount="20" CompletionInterval="1000" EnableCaching="true" ></ajaxToolkit:AutoCompleteExtender>
                                            </td>
										</tr>
										<tr>
											<td align="center"><asp:button id="btnLoadName" runat="server" Text="2. Load name" 
                                                    onclick="btnLoadName_Click" CssClass="btnBox"/></td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="4">
					    <asp:GridView ID="gvAltName" runat="server" OnRowUpdating="gvAltName_OnRowUpdating" 
					        OnRowEditing="gvAltName_OnRowEditing" OnRowDeleting="gvAltName_OnRowDeleting" 
					        OnRowCancelingEdit="gvAltName_OnRowCancelingEdit" DataKeyNames="OA_ID" 
					        EmptyDataText="No alternate names" AutoGenerateColumns="false" 
					        AutoGenerateDeleteButton="true" AutoGenerateEditButton="true">
					        <AlternatingRowStyle HorizontalAlign="Left" BackColor="Silver" />
					        <HeaderStyle Font-Size="Medium" Font-Names="Verdana" Font-Bold="true" HorizontalAlign="Left"
					            Height="10px" ForeColor="Black" BackColor="Silver" />
					        <Columns>
					            <asp:BoundField DataField="OA_ALTNAME" HeaderText="Alternate Name" />
					        </Columns>    
					    </asp:GridView>
					</td>
					<td valign="top" align="left">
						<table class="obaTableCls2">
							<tr>
								<td align="center"><asp:textbox id="txtNewAltName" Width="225px" Runat="server" CssClass="txtBox"></asp:textbox></td>
							</tr>
							<tr>
								<td><asp:button id="btnNewAltname" Text="3. Enter New Alternate Name" 
                                        Runat="server" onclick="btnNewAltname_Click" CssClass="btnBox"></asp:button></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td valign="top" colspan="4">
					    <asp:GridView id="gvArticles" runat="server" OnRowEditing="gvArticles_OnRowEditing" 
					        OnRowDeleting="gvArticles_OnRowDeleting" OnRowCancelingEdit="gvArticles_OnRowCancelingEdit" 
					        OnRowUpdating="gvArticles_OnRowUpdating" DataKeyNames="OD_ID" AutoGenerateColumns="false" 
					        AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" EmptyDataText="No article dates">
					        <EditRowStyle Font-Size="Large" />
					        <AlternatingRowStyle BackColor="Silver" />
					        <HeaderStyle Font-Bold="True" ForeColor="Black" BackColor="Silver" />
					        <Columns>
					            <asp:BoundField DataField="N_ABBR" HeaderText="Newspaper" />
								<asp:BoundField DataField="OD_ARTICLE_DATE" HeaderText="Date Of Article" />
								<asp:BoundField DataField="OD_WEB_ENTRY" HeaderText="Web Text" />								
					        </Columns>    
					    </asp:GridView>
					</td>
					<td valign="top" align="left">
						<table class="obaTableCls2">
							<tr>
								<td align="center"><asp:label id="Label1" runat="server" Width="75px" Font-Underline="True">NewsPaper</asp:label></td>
								<td align="center"><asp:label id="Label2" runat="server" Width="101px" Font-Underline="True">Date of Article</asp:label></td>
							</tr>
							<tr>
								<td align="center"><asp:dropdownlist id="ddlNews" runat="server">
										<asp:ListItem Value="SPJ" Selected="True">SPJ</asp:ListItem>
										<asp:ListItem Value="SPWJ">SPWJ</asp:ListItem>
										<asp:ListItem Value="SPDJ">SPDJ</asp:ListItem>
										<asp:ListItem Value="SPG">SPG</asp:ListItem>
										<asp:ListItem Value="PCG">PCG</asp:ListItem>
									</asp:dropdownlist></td>
								<td align="center"><asp:textbox id="txtNewDate" runat="server" Width="120px" CssClass="txtBox"></asp:textbox></td>
							</tr>
							<tr>
								<td align="center" colspan="2"><asp:label id="Label4" runat="server" Font-Underline="True">Web Text</asp:label></td>
							</tr>
							<tr>
								<td colspan="2"><asp:textbox id="txtNewWeb" runat="server" Height="148px" Width="234px" Wrap="True" TextMode="MultiLine" CssClass="txtBox"></asp:textbox></td>
							</tr>
							<%--<tr>
								<td colspan="2"></td>
							</tr>
							<TR>
								<TD colspan="2"><asp:label id="Label3" runat="server" Font-Underline="True">Image File Name</asp:label></TD>
							</TR>
							<TR>
								<TD colspan="2"><input id="tbNewFile" runat="server" type="file" Width="233px">
								</TD>
							</TR>--%>
							<tr>
								<td colspan="2"><asp:button id="btnNewArticleDate" runat="server" 
                                        Text="4. Enter a New Newspaper Article" Width="234px" 
                                        onclick="btnNewArticleDate_Click" CssClass="btnBox"></asp:button></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
	</div>
</asp:Content>

