(function() {
    var h = void 0, j = !0, k = null, l = !1, m, n = this; function o() { }
    function p(a) {
        var b = typeof a; if ("object" == b) if (a) { if (a instanceof Array) return "array"; if (a instanceof Object) return b; var c = Object.prototype.toString.call(a); if ("[object Window]" == c) return "object"; if ("[object Array]" == c || "number" == typeof a.length && "undefined" != typeof a.splice && "undefined" != typeof a.propertyIsEnumerable && !a.propertyIsEnumerable("splice")) return "array"; if ("[object Function]" == c || "undefined" != typeof a.call && "undefined" != typeof a.propertyIsEnumerable && !a.propertyIsEnumerable("call")) return "function" } else return "null";
        else if ("function" == b && "undefined" == typeof a.call) return "object"; return b
    } function q(a) { return "array" == p(a) } function r(a) { var b = p(a); return "array" == b || "object" == b && "number" == typeof a.length } function s(a) { return "string" == typeof a } function aa(a) { var b = typeof a; return "object" == b && a != k || "function" == b } var ba = "closure_uid_" + Math.floor(2147483648 * Math.random()).toString(36), ca = 0; function da(a, b, c) { return a.call.apply(a.bind, arguments) }
    function ea(a, b, c) { if (!a) throw Error(); if (2 < arguments.length) { var d = Array.prototype.slice.call(arguments, 2); return function() { var c = Array.prototype.slice.call(arguments); Array.prototype.unshift.apply(c, d); return a.apply(b, c) } } return function() { return a.apply(b, arguments) } } function t(a, b, c) { t = Function.prototype.bind && -1 != Function.prototype.bind.toString().indexOf("native code") ? da : ea; return t.apply(k, arguments) }
    function fa(a, b) { var c = Array.prototype.slice.call(arguments, 1); return function() { var b = Array.prototype.slice.call(arguments); b.unshift.apply(b, c); return a.apply(this, b) } } var ga = Date.now || function() { return +new Date }; function x(a, b) { function c() { } c.prototype = b.prototype; a.T = b.prototype; a.prototype = new c }; function y(a) { Error.captureStackTrace ? Error.captureStackTrace(this, y) : this.stack = Error().stack || ""; a && (this.message = "" + a) } x(y, Error); y.prototype.name = "CustomError"; var ha = /^[a-zA-Z0-9\-_.!~*'()]*$/; function ia(a) { a = "" + a; return !ha.test(a) ? encodeURIComponent(a) : a } function ja(a) { if (!ka.test(a)) return a; -1 != a.indexOf("&") && (a = a.replace(la, "&amp;")); -1 != a.indexOf("<") && (a = a.replace(ma, "&lt;")); -1 != a.indexOf(">") && (a = a.replace(na, "&gt;")); -1 != a.indexOf('"') && (a = a.replace(oa, "&quot;")); return a } var la = /&/g, ma = /</g, na = />/g, oa = /\"/g, ka = /[&<>\"]/; function pa(a) { return ("" + a).replace(/\-([a-z])/g, function(a, c) { return c.toUpperCase() }) }; var z = Array.prototype, A = z.indexOf ? function(a, b, c) { return z.indexOf.call(a, b, c) } : function(a, b, c) { c = c == k ? 0 : 0 > c ? Math.max(0, a.length + c) : c; if (s(a)) return !s(b) || 1 != b.length ? -1 : a.indexOf(b, c); for (; c < a.length; c++) if (c in a && a[c] === b) return c; return -1 }, B = z.forEach ? function(a, b, c) { z.forEach.call(a, b, c) } : function(a, b, c) { for (var d = a.length, e = s(a) ? a.split("") : a, f = 0; f < d; f++) f in e && b.call(c, e[f], f, a) }, qa = z.filter ? function(a, b, c) { return z.filter.call(a, b, c) } : function(a, b, c) {
        for (var d = a.length, e = [], f = 0, g = s(a) ? a.split("") :
a, i = 0; i < d; i++) if (i in g) { var u = g[i]; b.call(c, u, i, a) && (e[f++] = u) } return e
    }, ra = z.map ? function(a, b, c) { return z.map.call(a, b, c) } : function(a, b, c) { for (var d = a.length, e = Array(d), f = s(a) ? a.split("") : a, g = 0; g < d; g++) g in f && (e[g] = b.call(c, f[g], g, a)); return e }, sa = z.some ? function(a, b, c) { return z.some.call(a, b, c) } : function(a, b, c) { for (var d = a.length, e = s(a) ? a.split("") : a, f = 0; f < d; f++) if (f in e && b.call(c, e[f], f, a)) return j; return l }; function C(a) { return z.concat.apply(z, arguments) }
    function ta(a) { if (q(a)) return C(a); for (var b = [], c = 0, d = a.length; c < d; c++) b[c] = a[c]; return b } function ua(a, b, c) { return 2 >= arguments.length ? z.slice.call(a, b) : z.slice.call(a, b, c) } function va(a) { for (var b = {}, c = 0, d = 0; d < a.length; ) { var e = a[d++], f = aa(e) ? "o" + (e[ba] || (e[ba] = ++ca)) : (typeof e).charAt(0) + e; Object.prototype.hasOwnProperty.call(b, f) || (b[f] = j, a[c++] = e) } a.length = c }; function D(a, b) { for (var c in a) b.call(h, a[c], c, a) } function wa(a) { var b = [], c = 0, d; for (d in a) b[c++] = a[d]; return b } function xa(a) { var b = [], c = 0, d; for (d in a) b[c++] = d; return b } var ya = "constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(","); function E(a, b) { for (var c, d, e = 1; e < arguments.length; e++) { d = arguments[e]; for (c in d) a[c] = d[c]; for (var f = 0; f < ya.length; f++) c = ya[f], Object.prototype.hasOwnProperty.call(d, c) && (a[c] = d[c]) } }; function za(a) { if ("function" == typeof a.l) return a.l(); if (s(a)) return a.split(""); if (r(a)) { for (var b = [], c = a.length, d = 0; d < c; d++) b.push(a[d]); return b } return wa(a) } function Aa(a, b, c) { if ("function" == typeof a.forEach) a.forEach(b, c); else if (r(a) || s(a)) B(a, b, c); else { var d; if ("function" == typeof a.o) d = a.o(); else if ("function" != typeof a.l) if (r(a) || s(a)) { d = []; for (var e = a.length, f = 0; f < e; f++) d.push(f) } else d = xa(a); else d = h; for (var e = za(a), f = e.length, g = 0; g < f; g++) b.call(c, e[g], d && d[g], a) } }; function F(a, b) { this.h = {}; this.c = []; var c = arguments.length; if (1 < c) { if (c % 2) throw Error("Uneven number of arguments"); for (var d = 0; d < c; d += 2) this.set(arguments[d], arguments[d + 1]) } else if (a) { a instanceof F ? (c = a.o(), d = a.l()) : (c = xa(a), d = wa(a)); for (var e = 0; e < c.length; e++) this.set(c[e], d[e]) } } m = F.prototype; m.b = 0; m.l = function() { Ba(this); for (var a = [], b = 0; b < this.c.length; b++) a.push(this.h[this.c[b]]); return a }; m.o = function() { Ba(this); return this.c.concat() }; m.i = function(a) { return G(this.h, a) };
    m.remove = function(a) { return G(this.h, a) ? (delete this.h[a], this.b--, this.c.length > 2 * this.b && Ba(this), j) : l }; function Ba(a) { if (a.b != a.c.length) { for (var b = 0, c = 0; b < a.c.length; ) { var d = a.c[b]; G(a.h, d) && (a.c[c++] = d); b++ } a.c.length = c } if (a.b != a.c.length) { for (var e = {}, c = b = 0; b < a.c.length; ) d = a.c[b], G(e, d) || (a.c[c++] = d, e[d] = 1), b++; a.c.length = c } } m.get = function(a, b) { return G(this.h, a) ? this.h[a] : b }; m.set = function(a, b) { G(this.h, a) || (this.b++, this.c.push(a)); this.h[a] = b }; m.n = function() { return new F(this) };
    function G(a, b) { return Object.prototype.hasOwnProperty.call(a, b) }; var H, Ca, Da, Ea; function Fa() { return n.navigator ? n.navigator.userAgent : k } Ea = Da = Ca = H = l; var Ga; if (Ga = Fa()) { var Ha = n.navigator; H = 0 == Ga.indexOf("Opera"); Ca = !H && -1 != Ga.indexOf("MSIE"); Da = !H && -1 != Ga.indexOf("WebKit"); Ea = !H && !Da && "Gecko" == Ha.product } var Ia = H, I = Ca, Ja = Ea, Ka = Da, La;
    a: { var Ma = "", J; if (Ia && n.opera) var Na = n.opera.version, Ma = "function" == typeof Na ? Na() : Na; else if (Ja ? J = /rv\:([^\);]+)(\)|;)/ : I ? J = /MSIE\s+([^\);]+)(\)|;)/ : Ka && (J = /WebKit\/(\S+)/), J) var Oa = J.exec(Fa()), Ma = Oa ? Oa[1] : ""; if (I) { var Pa, Qa = n.document; Pa = Qa ? Qa.documentMode : h; if (Pa > parseFloat(Ma)) { La = "" + Pa; break a } } La = Ma } var Ra = {};
    function Sa(a) {
        var b; if (!(b = Ra[a])) {
            b = 0; for (var c = ("" + La).replace(/^[\s\xa0]+|[\s\xa0]+$/g, "").split("."), d = ("" + a).replace(/^[\s\xa0]+|[\s\xa0]+$/g, "").split("."), e = Math.max(c.length, d.length), f = 0; 0 == b && f < e; f++) {
                var g = c[f] || "", i = d[f] || "", u = RegExp("(\\d*)(\\D*)", "g"), Jb = RegExp("(\\d*)(\\D*)", "g"); do {
                    var v = u.exec(g) || ["", "", ""], w = Jb.exec(i) || ["", "", ""]; if (0 == v[0].length && 0 == w[0].length) break; b = ((0 == v[1].length ? 0 : parseInt(v[1], 10)) < (0 == w[1].length ? 0 : parseInt(w[1], 10)) ? -1 : (0 == v[1].length ? 0 : parseInt(v[1],
10)) > (0 == w[1].length ? 0 : parseInt(w[1], 10)) ? 1 : 0) || ((0 == v[2].length) < (0 == w[2].length) ? -1 : (0 == v[2].length) > (0 == w[2].length) ? 1 : 0) || (v[2] < w[2] ? -1 : v[2] > w[2] ? 1 : 0)
                } while (0 == b)
            } b = Ra[a] = 0 <= b
        } return b
    } var Ta = {}; function Ua() { return Ta[9] || (Ta[9] = I && !!document.documentMode && 9 <= document.documentMode) }; var Va = RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"); function K(a, b) { var c; a instanceof K ? (this.q(b == k ? a.f : b), Wa(this, a.j), Xa(this, a.z), Ya(this, a.k), Za(this, a.p), $a(this, a.m), ab(this, a.d.n()), bb(this, a.t)) : a && (c = ("" + a).match(Va)) ? (this.q(!!b), Wa(this, c[1] || "", j), Xa(this, c[2] || "", j), Ya(this, c[3] || "", j), Za(this, c[4]), $a(this, c[5] || "", j), ab(this, c[6] || "", j), bb(this, c[7] || "", j)) : (this.q(!!b), this.d = new L(k, this, this.f)) } m = K.prototype; m.j = ""; m.z = ""; m.k = ""; m.p = k; m.m = ""; m.t = ""; m.P = l; m.f = l;
    m.toString = function() { if (this.e) return this.e; var a = []; this.j && a.push(M(this.j, cb), ":"); this.k && (a.push("//"), this.z && a.push(M(this.z, cb), "@"), a.push(s(this.k) ? encodeURIComponent(this.k) : k), this.p != k && a.push(":", "" + this.p)); this.m && (this.k && "/" != this.m.charAt(0) && a.push("/"), a.push(M(this.m, "/" == this.m.charAt(0) ? db : eb))); var b = "" + this.d; b && a.push("?", b); this.t && a.push("#", M(this.t, fb)); return this.e = a.join("") };
    m.n = function() { var a = this.j, b = this.z, c = this.k, d = this.p, e = this.m, f = this.d.n(), g = this.t, i = new K(k, this.f); a && Wa(i, a); b && Xa(i, b); c && Ya(i, c); d && Za(i, d); e && $a(i, e); f && ab(i, f); g && bb(i, g); return i }; function Wa(a, b, c) { N(a); delete a.e; a.j = c ? b ? decodeURIComponent(b) : "" : b; a.j && (a.j = a.j.replace(/:$/, "")) } function Xa(a, b, c) { N(a); delete a.e; a.z = c ? b ? decodeURIComponent(b) : "" : b } function Ya(a, b, c) { N(a); delete a.e; a.k = c ? b ? decodeURIComponent(b) : "" : b }
    function Za(a, b) { N(a); delete a.e; if (b) { b = Number(b); if (isNaN(b) || 0 > b) throw Error("Bad port number " + b); a.p = b } else a.p = k } function $a(a, b, c) { N(a); delete a.e; a.m = c ? b ? decodeURIComponent(b) : "" : b } function ab(a, b, c) { N(a); delete a.e; b instanceof L ? (a.d = b, a.d.w = a, a.d.q(a.f)) : (c || (b = M(b, gb)), a.d = new L(b, a, a.f)) } function hb(a, b, c) { N(a); delete a.e; q(c) || (c = ["" + c]); a = a.d; O(a); P(a); b = Q(a, b); if (a.i(b)) { var d = a.a.get(b); q(d) ? a.b -= d.length : a.b-- } 0 < c.length && (a.a.set(b, c), a.b += c.length) }
    function bb(a, b, c) { N(a); delete a.e; a.t = c ? b ? decodeURIComponent(b) : "" : b } function N(a) { if (a.P) throw Error("Tried to modify a read-only Uri"); } m.q = function(a) { this.f = a; this.d && this.d.q(a); return this }; var ib = /^[a-zA-Z0-9\-_.!~*'():\/;?]*$/; function M(a, b) { var c = k; s(a) && (c = a, ib.test(c) || (c = encodeURI(a)), 0 <= c.search(b) && (c = c.replace(b, jb))); return c } function jb(a) { a = a.charCodeAt(0); return "%" + (a >> 4 & 15).toString(16) + (a & 15).toString(16) } var cb = /[#\/\?@]/g, eb = /[\#\?:]/g, db = /[\#\?]/g, gb = /[\#\?@]/g, fb = /#/g;
    function L(a, b, c) { this.g = a || k; this.w = b || k; this.f = !!c } function O(a) { if (!a.a && (a.a = new F, a.b = 0, a.g)) for (var b = a.g.split("&"), c = 0; c < b.length; c++) { var d = b[c].indexOf("="), e = k, f = k; 0 <= d ? (e = b[c].substring(0, d), f = b[c].substring(d + 1)) : e = b[c]; e = decodeURIComponent(e.replace(/\+/g, " ")); e = Q(a, e); a.add(e, f ? decodeURIComponent(f.replace(/\+/g, " ")) : "") } } m = L.prototype; m.a = k; m.b = k;
    m.add = function(a, b) { O(this); P(this); a = Q(this, a); if (this.i(a)) { var c = this.a.get(a); q(c) ? c.push(b) : this.a.set(a, [c, b]) } else this.a.set(a, b); this.b++; return this }; m.remove = function(a) { O(this); a = Q(this, a); if (this.a.i(a)) { P(this); var b = this.a.get(a); q(b) ? this.b -= b.length : this.b--; return this.a.remove(a) } return l }; m.i = function(a) { O(this); a = Q(this, a); return this.a.i(a) };
    m.o = function() { O(this); for (var a = this.a.l(), b = this.a.o(), c = [], d = 0; d < b.length; d++) { var e = a[d]; if (q(e)) for (var f = 0; f < e.length; f++) c.push(b[d]); else c.push(b[d]) } return c }; m.l = function(a) { O(this); var b = []; if (a) a = Q(this, a), this.i(a) && (b = C(b, this.a.get(a))); else for (var a = this.a.l(), c = 0; c < a.length; c++) b = C(b, a[c]); return b }; m.set = function(a, b) { O(this); P(this); a = Q(this, a); if (this.i(a)) { var c = this.a.get(a); q(c) ? this.b -= c.length : this.b-- } this.a.set(a, b); this.b++; return this };
    m.get = function(a, b) { O(this); a = Q(this, a); if (this.i(a)) { var c = this.a.get(a); return q(c) ? c[0] : c } return b }; m.toString = function() { if (this.g) return this.g; if (!this.a) return ""; for (var a = [], b = 0, c = this.a.o(), d = 0; d < c.length; d++) { var e = c[d], f = ia(e), e = this.a.get(e); if (q(e)) for (var g = 0; g < e.length; g++) 0 < b && a.push("&"), a.push(f), "" !== e[g] && a.push("=", ia(e[g])), b++; else 0 < b && a.push("&"), a.push(f), "" !== e && a.push("=", ia(e)), b++ } return this.g = a.join("") }; function P(a) { delete a.B; delete a.g; a.w && delete a.w.e }
    function kb(a) { var b = lb; O(a); Aa(a.a, function(a, d) { 0 <= A(b, d) || this.remove(d) }, a) } m.n = function() { var a = new L; this.B && (a.B = this.B); this.g && (a.g = this.g); this.a && (a.a = this.a.n()); return a }; function Q(a, b) { var c = "" + b; a.f && (c = c.toLowerCase()); return c } m.q = function(a) { a && !this.f && (O(this), P(this), Aa(this.a, function(a, c) { var d = c.toLowerCase(); c != d && (this.remove(c), this.add(d, a)) }, this)); this.f = a }; var mb = !I || Ua(); !Ja && !I || I && Ua() || Ja && Sa("1.9.1"); I && Sa("9"); function nb(a) { a = a.className; return s(a) && a.match(/\S+/g) || [] } function ob(a, b) { for (var c = nb(a), d = ua(arguments, 1), e = c.length + d.length, f = c, g = 0; g < d.length; g++) 0 <= A(f, d[g]) || f.push(d[g]); a.className = c.join(" "); return c.length == e } function pb(a, b) { var c = nb(a), d = ua(arguments, 1), c = qb(c, d); a.className = c.join(" ") } function qb(a, b) { return qa(a, function(a) { return !(0 <= A(b, a)) }) }; function rb() { return s("libraryh3lp") ? document.getElementById("libraryh3lp") : "libraryh3lp" }
    function R(a, b) {
        var c = document, d = a && "*" != a ? a.toUpperCase() : ""; if (c.querySelectorAll && c.querySelector && (!Ka || "CSS1Compat" == document.compatMode || Sa("528")) && (d || b)) return c.querySelectorAll(d + (b ? "." + b : "")); if (b && c.getElementsByClassName) { c = c.getElementsByClassName(b); if (d) { for (var e = {}, f = 0, g = 0, i; i = c[g]; g++) d == i.nodeName && (e[f++] = i); e.length = f; return e } return c } c = c.getElementsByTagName(d || "*"); if (b) {
            e = {}; for (g = f = 0; i = c[g]; g++) d = i.className, "function" == typeof d.split && 0 <= A(d.split(/\s+/), b) && (e[f++] = i);
            e.length = f; return e
        } return c
    } function sb(a, b) { D(b, function(b, d) { "style" == d ? a.style.cssText = b : "class" == d ? a.className = b : "for" == d ? a.htmlFor = b : d in tb ? a.setAttribute(tb[d], b) : 0 == d.lastIndexOf("aria-", 0) ? a.setAttribute(d, b) : a[d] = b }) } var tb = { cellpadding: "cellPadding", cellspacing: "cellSpacing", colspan: "colSpan", rowspan: "rowSpan", valign: "vAlign", height: "height", width: "width", usemap: "useMap", frameborder: "frameBorder", maxlength: "maxLength", type: "type" };
    function ub(a, b, c) { function d(c) { c && b.appendChild(s(c) ? a.createTextNode(c) : c) } for (var e = 2; e < c.length; e++) { var f = c[e]; r(f) && !(aa(f) && 0 < f.nodeType) ? B(vb(f) ? ta(f) : f, d) : d(f) } } function vb(a) { if (a && "number" == typeof a.length) { if (aa(a)) return "function" == typeof a.item || "string" == typeof a.item; if ("function" == p(a)) return "function" == typeof a.item } return l } function S(a) { this.C = a || n.document || document }
    S.prototype.H = function(a, b, c) { var d = this.C, e = arguments, f = e[0], g = e[1]; if (!mb && g && (g.name || g.type)) { f = ["<", f]; g.name && f.push(' name="', ja(g.name), '"'); if (g.type) { f.push(' type="', ja(g.type), '"'); var i = {}; E(i, g); g = i; delete g.type } f.push(">"); f = f.join("") } f = d.createElement(f); g && (s(g) ? f.className = g : q(g) ? ob.apply(k, [f].concat(g)) : sb(f, g)); 2 < e.length && ub(d, f, e); return f }; S.prototype.createElement = function(a) { return this.C.createElement(a) }; S.prototype.createTextNode = function(a) { return this.C.createTextNode(a) };
    S.prototype.appendChild = function(a, b) { a.appendChild(b) }; /*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
    function wb(a, b) { this.A = []; this.O = b || k } m = wb.prototype; m.s = l; m.u = l; m.v = 0; m.J = l; m.M = l; m.K = 0; m.G = function(a, b) { xb(this, a, b); this.v--; 0 == this.v && this.s && yb(this) }; function xb(a, b, c) { a.s = j; a.D = c; a.u = !b; yb(a) } function zb(a) { if (a.s) { if (!a.J) throw new Ab; a.J = l } } function Bb(a, b, c, d) { a.A.push([b, c, d]); a.s && yb(a) } function Cb(a) { return sa(a.A, function(a) { return "function" == p(a[1]) }) }
    function yb(a) { a.F && a.s && Cb(a) && (n.clearTimeout(a.F), delete a.F); a.I && (a.I.K--, delete a.I); for (var b = a.D, c = l, d = l; a.A.length && 0 == a.v; ) { var e = a.A.shift(), f = e[0], g = e[1], e = e[2]; if (f = a.u ? g : f) try { var i = f.call(e || a.O, b); i !== h && (a.u = a.u && (i == b || i instanceof Error), a.D = b = i); b instanceof wb && (d = j, a.v++) } catch (u) { b = u, a.u = j, Cb(a) || (c = j) } } a.D = b; d && a.v && (Bb(b, t(a.G, a, j), t(a.G, a, l)), b.M = j); c && (a.F = n.setTimeout(function() { throw new Db(b); }, 0)) } function Ab() { y.call(this) } x(Ab, y); Ab.prototype.message = "Already called";
    function Db(a) { y.call(this); this.message = "Unhandled Error in Deferred: " + (a.message || "[No message]") } x(Db, y); function Eb(a, b) {
        var c = b || {}, d = c.document || document, e = document.createElement("SCRIPT"), f = { S: e, r: h }, g = new wb(0, f), i = k, u = c.timeout != k ? c.timeout : 5E3; 0 < u && (i = window.setTimeout(function() { Fb(e, j); var b = new Gb(Hb, "Timeout reached for loading script " + a); zb(g); xb(g, l, b) }, u), f.r = i); e.onload = e.onreadystatechange = function() { if (!e.readyState || e.readyState == "loaded" || e.readyState == "complete") { Fb(e, c.N || l, i); zb(g); xb(g, j, k) } }; e.onerror = function() {
            Fb(e, j, i); var b = new Gb(Ib, "Error while loading script " + a); zb(g);
            xb(g, l, b)
        }; sb(e, { type: "text/javascript", charset: "UTF-8", src: a }); Kb(d).appendChild(e); return g
    } function Kb(a) { var b = a.getElementsByTagName("HEAD"); return !b || 0 == b.length ? a.documentElement : b[0] } function Fb(a, b, c) { c != k && n.clearTimeout(c); a.onload = o; a.onerror = o; a.onreadystatechange = o; b && window.setTimeout(function() { a && a.parentNode && a.parentNode.removeChild(a) }, 0) } var Ib = 0, Hb = 1; function Gb(a, b) { var c = "Jsloader error (code #" + a + ")"; b && (c += ": " + b); y.call(this, c); this.code = a } x(Gb, y); function Lb(a, b) { this.w = new K(a); this.L = b ? b : "callback"; this.r = 5E3 } var Mb = 0; Lb.prototype.send = function(a, b, c, d) { a = a || k; d = d || "_" + (Mb++).toString(36) + ga().toString(36); n._callbacks_ || (n._callbacks_ = {}); var e = this.w.n(); if (a) for (var f in a) (!a.hasOwnProperty || a.hasOwnProperty(f)) && hb(e, f, a[f]); b && (n._callbacks_[d] = Nb(d, b), hb(e, this.L, "_callbacks_." + d)); b = Eb(e.toString(), { timeout: this.r, N: j }); Bb(b, k, Ob(d, a, c), h); return { R: d, Q: b} }; function Ob(a, b, c) { return function() { Pb(a, l); c && c(b) } }
    function Nb(a, b) { return function(c) { Pb(a, j); b.apply(h, arguments) } } function Pb(a, b) { n._callbacks_[a] && (b ? delete n._callbacks_[a] : n._callbacks_[a] = o) }; function Qb(a, b, c) { a.style[pa(c)] = b } function Rb(a, b) { a.style.display = b ? "" : "none" }; var Sb; Sb = l; var T = Fa(); T && (-1 != T.indexOf("Firefox") || -1 != T.indexOf("Camino") || -1 != T.indexOf("iPhone") || -1 != T.indexOf("iPod") || -1 != T.indexOf("iPad") || -1 != T.indexOf("Android") || -1 != T.indexOf("Chrome") || -1 != T.indexOf("Safari") && (Sb = j)); var Tb = Ia, Ub = I, Vb = Sb; var lb = "client_id,css,identity,profile,referer,sounds,theme,title".split(","), Wb = k, U = "http://libraryh3lp.com", V = {}, W = l, Xb = l, Yb = []; function X() { W || (W = j, B(Yb, function(a) { a.call(window, []) }), Yb = []) } function Zb() { var a = X, b = window.onload; window.onload = "function" != typeof window.onload ? a : function() { b && b(); a() } }
    function $b() {
        if (!Xb) {
            Xb = j; document.addEventListener && !Tb && document.addEventListener("DOMContentLoaded", X, l); Ub && window == top && function() { if (!W) { try { document.documentElement.doScroll("left") } catch (a) { setTimeout(arguments.callee, 0); return } X() } } (); Tb && document.addEventListener("DOMContentLoaded", function() { if (!W) { for (var a = 0; a < document.styleSheets.length; a++) if (document.styleSheets[a].disabled) { setTimeout(arguments.callee, 0); return } X() } }, l); if (Vb) {
                var a; (function() {
                    if (!W) if ("loaded" != document.readyState &&
"complete" != document.readyState) setTimeout(arguments.callee, 0); else { if (a === h) { for (var b = document.getElementsByTagName("link"), c = 0; c < b.length; c++) "stylesheet" == b[c].getAttribute("rel") && a++; a += document.getElementsByTagName("style").length } document.styleSheets.length != a ? setTimeout(arguments.callee, 0) : X() } 
                })()
            } Zb()
        } 
    } function ac() { var a = bc; $b(); W ? a.call(window, []) : Yb.push(function() { return a.call(window, []) }) }
    function cc() { return sa(window.jabber_resources || [], function(a) { return 0 <= A(["chat", "available"], a.show) }) } function dc(a) { var b = rb().getAttribute("jid"), b = new K([U, "chat", b].join("/")), c = b.d; D(a, function(b, e) { Object.prototype.hasOwnProperty.call(a, e) && c.add(e, b) }); kb(c); return b.toString() } function ec() { var a = R("*", "libraryh3lp"); if (0 < a.length) { var a = q(a) ? C(a) : ta(a), b = ra(a, function(a) { return a.getAttribute("jid") }); va(b); fc(b, a) } else gc() }
    function fc(a, b) { if (0 === a.length) B(b, function(a) { Rb(a, !a.getAttribute("jid")) }); else { var c = a.shift(); if (c) { var d = c.split("@"), d = new Lb([U, "presence/jid", d[0], d[1], "js"].join("/"), "cb"), e = function() { cc() ? B(b, function(a) { Rb(a, a.getAttribute("jid") === c) }) : (B(b, function(a) { a.getAttribute("jid") === c && Rb(a, l) }), fc(a, b)) }; d.r = 6E4; d.send(k, e, e) } else fc(a, b) } }
    function gc() { var a = rb(); if (a) { var b = a.getAttribute("jid").split("@"), b = new Lb([U, "presence/jid", b[0], b[1], "js"].join("/"), "cb"), c = function() { cc() ? ob(a, "libraryh3lp_online") : (pb(a, "libraryh3lp_online"), Wb || gc()) }; window.jabber_client_id && !Wb ? (b.r = 6E4, b.send({ client_id: window.jabber_client_id }, c, c)) : (b.r = 3E4, b.send(k, c, c)) } } function hc(a) { var b = R("*", "needs-js"); 0 < b.length && (b[0].innerHTML = a.body, Rb(b[0], j), E(V, a.options), ic()) } function jc() { V.poll && (Wb = setInterval(function() { ec() }, 3E4)); ec() }
    function ic() { V.presence && document.write('<style type="text/css">\n.online, .libraryh3lp_online .offline { display: none; }\n.offline, .libraryh3lp_online .online { display: block; }\n</style>'); jc() }
    function bc() { var a = R("*", "needs-js"); B(a, function(a) { s("display") ? Qb(a, "none", "display") : D("display", fa(Qb, a)) }); var a = R("script", h), b = /\/js\/libraryh3lp\.js(\?.*)?$/, c = l, d = l; B(a, function(a) { if ((a = a.src) && a.match(b)) U = a.replace(b, ""), c = a.match(/\?([0-9]+)/), d = a.match(/\?([a-z,]+)/) }); c ? (new Lb([U, "presence/service", c[1]].join("/"))).send(k, hc) : (B((d ? d[1] : "presence,popup").split(","), function(a) { V[a] = j }), ic()) }
    setTimeout(function() { rb() || 0 < R("*", "libraryh3lp").length || 0 < R("*", "needs-js").length ? bc() : ac() }, 0);
    function kc(a, b) {
        if (V.popup) { var c = { page: window.location.href }; E(c, b); var d = new K(a); d.d.add("referer", window.location.href); c.chat = d.toString(); var e = new S, f = e.H("form", { action: U + "/follow", method: "post", style: "display: none;" }); e.appendChild(document.body, f); D(c, function(a, b) { if (Object.prototype.hasOwnProperty.call(c, b)) { var d = e.H("input", { type: "hidden", name: b, value: a }); e.appendChild(f, d) } }); f.submit() } else {
            c = { width: 400, height: 320 }; V = a; E(c, V); var g = []; D(c, function(a, b) {
                Object.prototype.hasOwnProperty.call(c,
b) && (0 <= A(lb, b) || g.push(b + "=" + a))
            }); window.open(dc(c), "libraryh3lp", g.join(","))
        } return l
    } var Y = ["libraryh3lp", "openChat"], Z = n; !(Y[0] in Z) && Z.execScript && Z.execScript("var " + Y[0]); for (var $; Y.length && ($ = Y.shift()); ) !Y.length && kc !== h ? Z[$] = kc : Z = Z[$] ? Z[$] : Z[$] = {};
})();